In [2]:
#pip install numpy

In [2]:
import numpy as np

In [3]:
a=np.array([1,11,12])
print(type(a))

<class 'numpy.ndarray'>


In [4]:
print(a)

[ 1 11 12]


In [51]:
c=np.array([(23,22,1),(2,1,4),(5,6,7)])
print(type(c))

<class 'numpy.ndarray'>


In [52]:
print(c)

[[23 22  1]
 [ 2  1  4]
 [ 5  6  7]]


In [7]:
r=c.ravel()

In [8]:
print(r)

[23 22  1  2  1  4]


In [9]:
zeromatrix=np.zeros((3,3))

In [10]:
print(zeromatrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
one=np.ones((2,2))

In [12]:
one

array([[1., 1.],
       [1., 1.]])

In [14]:
ins=np.insert(a,1,10)

In [15]:
ins

array([ 1, 10, 11, 12])

In [16]:
np.append(c,one)

array([23., 22.,  1.,  2.,  1.,  4.,  1.,  1.,  1.,  1.])

In [42]:
txt=np.array([(1,2,3),(2,3,4)])

In [43]:
txt

array([[1, 2, 3],
       [2, 3, 4]])

In [48]:
np.concatenate((txt,txt),axis=1)

array([[1, 2, 3, 1, 2, 3],
       [2, 3, 4, 2, 3, 4]])

In [44]:
np.concatenate((txt,txt),axis=None)

array([1, 2, 3, 2, 3, 4, 1, 2, 3, 2, 3, 4])

# Stack

In [35]:
np.hstack((c,c))

array([[23, 22,  1, 23, 22,  1],
       [ 2,  1,  4,  2,  1,  4]])

In [36]:
np.vstack((a,a))

array([[ 1, 11, 12],
       [ 1, 11, 12]])

In [56]:
#split
np.split(c,3)

[array([[23, 22,  1]]), array([[2, 1, 4]]), array([[5, 6, 7]])]

In [65]:
#Empty
np.empty((2,2))

array([[0.0e+000, 4.9e-324],
       [9.9e-324, 1.5e-323]])

In [62]:
ran=np.random.random((50,30))

In [63]:
print(ran)

[[0.67101106 0.65321463 0.55303381 ... 0.99448013 0.1607218  0.02661938]
 [0.81569853 0.10792988 0.96531516 ... 0.87026174 0.2794355  0.57282558]
 [0.18366138 0.50064665 0.5791673  ... 0.61953458 0.85338558 0.68318484]
 ...
 [0.62669568 0.28883535 0.99493988 ... 0.79870745 0.00954957 0.57419438]
 [0.05195817 0.94618272 0.86850884 ... 0.59941979 0.5869067  0.00451967]
 [0.81954572 0.80457942 0.51003625 ... 0.6334322  0.10090494 0.39525292]]
