In [2]:
#pip install numpy

In [3]:
import numpy as np

In [4]:
a=np.array([1,11,12])
print(type(a))

<class 'numpy.ndarray'>


In [5]:
print(a)

[ 1 11 12]


In [10]:
c=np.array([(23,22,1),(2,1,4)])
print(type(c))

<class 'numpy.ndarray'>


In [11]:
print(c)

[[23 22  1]
 [ 2  1  4]]


In [12]:
r=c.ravel()

In [13]:
print(r)

[23 22  1  2  1  4]
